### PR TITLE
Remove colorize

### PR DESCRIPTION
**Pull request by snayrouz**
@mikeyduece I like that map you shared. I thought I planned a better this time around, but after today, I got excited about Modules and self and now things just aren't going my way. I'm going to take colorize out just to make sure that has nothing to do with anything.

### CODE REVIEW

**Comment by snayrouz** [comment]
@AliSchlereth i refactored too much and broke it. Classic case of implementing something I saw in class and now nothing works. I'm still struggling with require vs require_relative. Add Modules to that mix, and now it's an extra layer of confusion with require/require_relative (side_note: please don't look at my tests 👎 ) . Any advice?

**Comment by AliSchlereth** [comment]
@snayrouz 
I haven't done a thorough review, but just from a quick peak I saw a few things. 
-You have some merge conflicts in your Messages module  
-It looks like some of the methods in there use self. and some don't.  Is this intentional? 
-Also, in battleshipv2.rb you require './lib/game' and later you call game.some_method but I don't see you create an instance of your Game class  

-As far as require and require_relative, I didn't look at all your files, but the three I looked at seemed fine.  Remember to run your battleshipv2.rb from the root of your project.  That would look something like `ruby ./lib/battleshipv2.rb`

**Comment by snayrouz** [comment]
@AliSchlereth I'll take a look at how that merge conflict is happening because you're right, the self. should not be there. 
- You're also right with the instance of Game class.

Thanks for the help!

**Comment by AliSchlereth** [comment]
@snayrouz  Also, remember that if you are calling `Messages.welcome` then in your Messages module it would be `def self.welcome` but if you want to just call `welcome` then in your Messages module is can say `def welcome` 

For example: 
Messages.welcome    would be      def self.welcome ... 
welcome                      would be      def welcome ...

**Pull request merged**
